question_data =[
 {'question': 'The Great Wall of China is visible from the moon.',
  'answer': 'False'},
 {'question': 'Video streaming website YouTube was purchased in it&#039;s entirety by Facebook for US$1.65 billion in stock.',
  'answer': 'False'},
 {'question': 'Gumbo is a stew that originated in Louisiana.',
  'answer': 'True'},
 {'question': 'It is automatically considered entrapment in the United States if the police sell you illegal substances without revealing themselves.',
  'answer': 'False'},
 {'question': 'Bulls are attracted to the color red.', 'answer': 'False'},
 {'question': '&quot;Ananas&quot; is mostly used as the word for Pineapple in other languages.',
  'answer': 'True'},
 {'question': 'You can legally drink alcohol while driving in Mississippi.',
  'answer': 'True'},
 {'question': 'Pluto is a planet.', 'answer': 'False'},
 {'question': 'Adolf Hitler was born in Australia. ', 'answer': 'False'},
 {'question': 'Romanian belongs to the Romance language family, shared with French, Spanish, Portuguese and Italian. ',
  'answer': 'True'},
 {'question': '&quot;27 Club&quot; is a term used to refer to a list of famous actors, musicians, and artists who died at the age of 27.',
  'answer': 'True'},
 {'question': 'Dihydrogen Monoxide was banned due to health risks after being discovered in 1983 inside swimming pools and drinking water.',
  'answer': 'False'},
 {'question': 'Scotland voted to become an independent country during the referendum from September 2014.',
  'answer': 'False'},
 {'question': 'Vietnam&#039;s national flag is a red star in front of a yellow background.',
  'answer': 'False'},
 {'question': 'Jingle Bells was originally meant for Thanksgiving',
  'answer': 'True'}]